version: '2'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin"

- command: generate-dist.sh
    plugins:
      - docker-compose#v3.3.0:
          run: app
          env:
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_PULL_REQUEST
            - MY_CUSTOM_ENV=llamas
